language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text
  - vendor/bin/phpcs --standard=PSR2 --extensions=php src tests
